function [y_x1x2] = bilinearInterpolation(x1,...
							              x2,...
						                  x1a_j,... 
						                  x1a_j1,...
						                  x2a_k,... 
						                  x2a_k1,...
						                  ya_jk,... 
						                  ya_j1k,...
						                  ya_j1k1,...
						                  ya_jk1)

	% Numerical Recipes in C++: The Art of Scientific Computing
    % Second Edition
    % 2002
    % Page 126 - 3.6 Interpolation in Two or More Dimensions 

	y0 = ya_jk;
	y1 = ya_j1k;
	y2 = ya_j1k1;
	y3 = ya_jk1;

	t = (x1 - x1a_j) / (x1a_j1 - x1a_j);

    u = (x2 - x2a_k) / (x2a_k1 - x2a_k);

	y_x1x2 = (1.0 - t) * (1.0 - u) * y0 + t * (1.0 - u) * y1 + t * u * y2 + (1.0 - t) * u * y3;

end