%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Design, modeling, and control of a low-cost air-bearing platform
%
% Software developed as part of the doctoral thesis.
%
% Author:      Luan Mateus Bocalan Vogás
% Advisor:     Prof. Dr. Roberto Kawakami Harrop Galvão
% Co-Advisor:  Profa. Dra. Gabriela Werner Gabriel
%
% Instituto Tecnológico de Aeronáutica (ITA)
% Electronics Engineering Division
% São José dos Campos, SP, Brazil
% 2026
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear all
close all
clc

%% System parameters

h = 0.125; % s
ts = 0.0521; % s
m = 1220.24/1000; % kg
g = 9.8066; % m/s^2
tractor_max_force = 0.2238; % N 
pusher_max_force = 0.1255; % N
max_duty_rw = 250; % Max delta duty cycle - reaction wheel

%% Actuators model

% Reaction wheel

load('Models\reaction wheel_model.mat')

% Drone motors

load('Models\drone_motors_model.mat')

%% DLQR rotational controller design

plot_enable = 0;
print_enable = 0;
max_ang_error = 60; % Degrees
uproj_r = max_duty_rw;

[K_rot] = DLQR_rotational_controller_design(Grw, ...
                                            h, ...
                                            ts, ...
                                            max_ang_error, ...
                                            uproj_r, ...
                                            plot_enable, ...
                                            print_enable)

csvwrite('Controllers/DLQRRotationalController.csv', K_rot)

%% DLQR translational controller design

plot_enable = 0;
print_enable = 0;
dist_max_error = 0.15; % m
uproj_t = tractor_max_force/4; 

[K_trans] = DLQR_translational_controller(m, ...
                                          Gm, ...
                                          h, ...
                                          ts, ...
                                          tm, ...
                                          dist_max_error, ...
                                          uproj_t, ...
                                          plot_enable, ...
                                          print_enable)

csvwrite('Controllers/DLQRTranslationalController.csv', K_trans)

%% DLMI code validation

validation = 0;

DLMI_code_validation(validation);

%% DLMI translational controller design

design_controller = 0;
plot_enable = 0;

[A_hat_r, ...
 B_hat_r, ... 
 C_hat_r, ...
 D_hat_r, ...
 Hinf_sim,...
 w0] = DLMI_translational_controller_design (m, ...
                                             Gm, ...
                                             ts, ...
                                             tm, ...
                                             h, ...
                                             design_controller, ...
                                             plot_enable)

%% Reference Tracking Simulation - DLQR Controller

plot_enable = 0;

[t_dlqr,...
 x_ref_dlqr,...
 y_ref_dlqr,...
 xmp_dlqr,...
 ymp_dlqr,...
 xc_dlqr,...
 yc_dlqr] = DLQR_reference_tracking_simulation(tractor_max_force, ...
                                               plot_enable);

%% Reference Tracking Simulation with Inclination Effect - DLQR Controller 

plot_enable = 0;

[t_dlqr_inc,...
 xmp_dlqr_inc,...
 ymp_dlqr_inc,...
 xc_dlqr_inc,...
 yc_dlqr_inc] = DLQR_reference_tracking_simulation_inclination(t_dlqr,...
                                                               x_ref_dlqr,...
                                                               y_ref_dlqr,...
                                                               xmp_dlqr,...
                                                               ymp_dlqr,...
                                                               xc_dlqr,...
                                                               yc_dlqr, ...
                                                               tractor_max_force, ...
                                                               plot_enable);

%% Reference Tracking Simulation with Inclination Compensation - DLQR Controller 

plot_enable = 0;

[t_dlqr_inc_comp,...
 xmp_dlqr_inc_comp,...
 ymp_dlqr_inc_comp,...
 xc_dlqr_inc_comp,...
 yc_dlqr_inc_comp] = DLQR_reference_tracking_simulation_inclination_compensation(t_dlqr,...
                                                                                 x_ref_dlqr,...
                                                                                 y_ref_dlqr,...
                                                                                 xmp_dlqr,...
                                                                                 ymp_dlqr,...
                                                                                 xmp_dlqr_inc,...
                                                                                 ymp_dlqr_inc,...
                                                                                 xc_dlqr,...
                                                                                 yc_dlqr,... 
                                                                                 tractor_max_force, ...
                                                                                 plot_enable);

%% Reference Tracking Simulation with Inclination Compensation and Noise - DLQR Controller 

plot_enable = 0;

[t_dlqr_inc_comp_noise,...
 xmp_dlqr_inc_comp_noise,...
 ymp_dlqr_inc_comp_noise,...
 xc_dlqr_inc_comp_noise,...
 yc_dlqr_inc_comp_noise] = DLQR_reference_tracking_simulation_noise_inc_comp(t_dlqr,...
                                                                             x_ref_dlqr,...
                                                                             y_ref_dlqr,...
                                                                             xmp_dlqr_inc_comp,...
                                                                             ymp_dlqr_inc_comp,...
                                                                             xc_dlqr_inc_comp,...
                                                                             yc_dlqr_inc_comp, ...
                                                                             tractor_max_force, ...
                                                                             plot_enable);

%% Experimental Reference Tracking - DLQR Controller without RW Control

plot_enable = 0;

DLQR_experimental_reference_tracking_without_rw(t_dlqr_inc,...
                                                xmp_dlqr_inc,...
                                                ymp_dlqr_inc,...
                                                plot_enable)

%% Experimental Reference Tracking - DLQR Controller

plot_enable = 0;

[t_dlqr_exp,...
 xmp_dlqr_exp,...
 ymp_dlqr_exp,...
 xcont_dlqr_exp,...
 ycont_dlqr_exp,...
 rot_ref_dlqr_exp,...
 rot_dlqr_exp,...
 rw_control_dlqr_exp] = DLQR_experimental_reference_tracking(t_dlqr_inc,...
                                                             x_ref_dlqr,...
                                                             y_ref_dlqr,...
                                                             xmp_dlqr_inc,...
                                                             ymp_dlqr_inc,...
                                                             xc_dlqr_inc,...
                                                             yc_dlqr_inc,...
                                                             tractor_max_force,...
                                                             plot_enable);

%% Experimental Reference Tracking with Inclination Compensation - DLQR Controller 

plot_enable = 0;

DLQR_experimental_reference_tracking_inclination_compensation(t_dlqr,...
                                                              t_dlqr_exp,...
                                                              x_ref_dlqr,...
                                                              y_ref_dlqr,...
                                                              xmp_dlqr_exp,...
                                                              ymp_dlqr_exp,...
                                                              xcont_dlqr_exp,...
                                                              ycont_dlqr_exp,...
                                                              rot_ref_dlqr_exp,...
                                                              rot_dlqr_exp,...
                                                              rw_control_dlqr_exp,...
                                                              tractor_max_force,...
                                                              plot_enable);

%% Disturbance Rejection - DLQR Controller

[t_dlqr_dr_sim,...
 xd_dlqr_dr_sim,...
 xmp_dlqr_dr_sim,...
 ymp_dlqr_dr_sim,...
 xc_dlqr_dr_sim,...
 yc_dlqr_dr_sim] = DLQR_disturbance_rejection_simulation();

%% Disturbance Rejection - DLMI Controller

[t_dlmi_dr_sim,...
 xd_dlmi_dr_sim,...
 xmp_dlmi_dr_sim,...
 ymp_dlmi_dr_sim,...
 xc_dlmi_dr_sim,...
 yc_dlmi_dr_sim] = DLMI_disturbance_rejection_simulation();

%% DLMI vs DLQR Numerical Comparison

plot_enable = 0;

DLMI_vs_DLQR_numerical_comparison(t_dlqr_dr_sim,...
                                  xd_dlqr_dr_sim,...
                                  xmp_dlqr_dr_sim,...
                                  ymp_dlqr_dr_sim,...
                                  xc_dlqr_dr_sim,...
                                  yc_dlqr_dr_sim, ...
                                  t_dlmi_dr_sim,...
                                  xd_dlmi_dr_sim,...
                                  xmp_dlmi_dr_sim,...
                                  ymp_dlmi_dr_sim,...
                                  xc_dlmi_dr_sim,...
                                  yc_dlmi_dr_sim,...
                                  tractor_max_force,...
                                  plot_enable)

%% Experimental Disturbance Rejection - DLQR Controller

[t_dlqr_dr_exp,...
 xmp_dlqr_dr_exp,...
 ymp_dlqr_dr_exp,...
 xc_dlqr_dr_exp,...
 yc_dlqr_dr_exp,...
 rot_dlqr_dr_exp,...
 rot_ref_dlqr_dr_exp,...
 rwc_dlqr_dr_exp] = DLQR_experimental_disturbance_rejection();

%% Experimental Disturbance Rejection - DLMI Controller

[t_dlmi_dr_exp,...
 xmp_dlmi_dr_exp,...
 ymp_dlmi_dr_exp,...
 xc_dlmi_dr_exp,...
 yc_dlmi_dr_exp,...
 rot_dlmi_dr_exp,...
 rot_ref_dlmi_dr_exp,...
 rwc_dlmi_dr_exp] = DLMI_experimental_disturbance_rejection();

%% Experimental Disturbance Rejection - Comparison of DLMI and DLQR Controllers

plot_enable = 0;

DLMI_vs_DLQR_experimental_comparison(t_dlqr_dr_exp,...
                                     xmp_dlqr_dr_exp,...
                                     ymp_dlqr_dr_exp,...
                                     xc_dlqr_dr_exp,...
                                     yc_dlqr_dr_exp, ...
                                     rot_dlqr_dr_exp,...
                                     rot_ref_dlqr_dr_exp,...
                                     rwc_dlqr_dr_exp,...
                                     t_dlmi_dr_exp,...
                                     xmp_dlmi_dr_exp,...
                                     ymp_dlmi_dr_exp,...
                                     xc_dlmi_dr_exp,...
                                     yc_dlmi_dr_exp,...
                                     rot_dlmi_dr_exp,...
                                     rot_ref_dlmi_dr_exp,...
                                     rwc_dlmi_dr_exp,...
                                     tractor_max_force,...
                                     plot_enable)

