function [currentIncX,currentIncY] = slopeDeterminationBasedOnCoordinates(x,y) 

    persistent incXAxis incYAxis

    if isempty(incXAxis)
        load('Matlab_data/inclinationGrid.mat');
    end
    
    resolution = 0.05;

    xGrid = -0.65:resolution:0.65;
    yGrid = -0.65:resolution:0.65;
    
    [xIndex, yIndex] = gridCoordinateSearch(x,...
                                            y,...
                                            xGrid,...
                                            yGrid);
    
    currentIncX = bilinearInterpolation(x,...
									    y,...
									    xGrid(xIndex),...
									    xGrid(xIndex + 1),...
									    yGrid(yIndex),...
									    yGrid(yIndex + 1),...
									    incXAxis(xIndex,yIndex),...
									    incXAxis(xIndex + 1,yIndex),...
									    incXAxis(xIndex + 1,yIndex + 1),...
									    incXAxis(xIndex,yIndex + 1));

    currentIncY = bilinearInterpolation(x,...
									    y,...
									    xGrid(xIndex),...
									    xGrid(xIndex + 1),...
									    yGrid(yIndex),...
									    yGrid(yIndex + 1),...
									    incYAxis(xIndex,yIndex),...
									    incYAxis(xIndex + 1,yIndex),...
									    incYAxis(xIndex + 1,yIndex + 1),...
									    incYAxis(xIndex,yIndex + 1));

end
