function [] = validation_gyroscope_calibration(t_gyro,...
                                               x_gyro,...
                                               y_gyro,...
                                               z_gyro,...
                                               t_servo,...
                                               v_servo,...
                                               plot_enable)
    if(plot_enable)    
        lw = 1.5;  
        figure
        set(gcf,'units','centimeters','position',[0,0,15,11])
        plot(t_servo(4:end-4),v_servo,'LineWidth',lw)
        hold on        
        plot(t_gyro,z_gyro,'LineWidth', lw)
        grid on
        xlabel('Time (s)','Interpreter','latex')
        ylabel('Angular Velocity ($\deg/$s)','Interpreter','latex')
        legend('Calculated from the encoder readings', 'Measured by the gyrometer',...
               'Location','southoutside','Orientation',...
               'horizontal','Interpreter','latex')
        xlim([0 5])
        saveas(gcf,'Figures/validation_gyroscope_calibration','epsc')
    end
end