%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Design, modeling, and control of a low-cost air-bearing platform
%
% Software developed as part of the doctoral thesis.
%
% Author:      Luan Mateus Bocalan Vogás
% Advisor:     Prof. Dr. Roberto Kawakami Harrop Galvão
% Co-Advisor:  Profa. Dra. Gabriela Werner Gabriel
%
% Instituto Tecnológico de Aeronáutica (ITA)
% Electronics Engineering Division
% São José dos Campos, SP, Brazil
% 2026
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear all
close all
clc

%% Representation of the plywood template

plot_enable = 0;

[glass_x,...
 glass_y,...
 plywood_x,...
 plywood_y,...
 plywood_division_x,...
 plywood_division_y,...
 nut_x,...
 nut_y] = plywood_template_representation(plot_enable);

%% Representation of central positions 

plot_enable = 0;

[x_central_useful,...
 y_central_useful] = central_position_template(glass_x,...
                                               glass_y,...
                                               plywood_x,...
                                               plywood_y,...
                                               plywood_division_x,...
                                               plywood_division_y,...
                                               nut_x,...
                                               nut_y,...
                                               plot_enable);

%% Data loading

[x,y,angles] = experimental_data_loading();

%% Validation of orientation measurements 

plot_enable = 0;

orientation_measurements_validation(x, ...
                                    y, ...
                                    angles, ...
                                    plot_enable)

%% Validation of position measurements 

plot_enable = 0;

[x_adj,y_adj] = position_measurements_validation(glass_x,...
                                                 glass_y,...
                                                 plywood_x,...
                                                 plywood_y,...
                                                 plywood_division_x,...
                                                 plywood_division_y,...
                                                 x_central_useful, ...
                                                 y_central_useful, ...
                                                 x, ...
                                                 y, ...
                                                 plot_enable);

%% Evaluation of the least squares fitting method 

plot_enable = 0;

least_squares_evaluation(glass_x,...
                         glass_y,...
                         plywood_x,...
                         plywood_y,...
                         plywood_division_x,...
                         plywood_division_y,...
                         x_central_useful, ...
                         y_central_useful, ...
                         x_adj, ...
                         y_adj, ...
                         plot_enable)

%% Least squares fitting with all data

plot_enable = 0;

[Ahatx,Ahaty] = least_squares_fitting(glass_x,...
                                      glass_y,...
                                      plywood_x,...
                                      plywood_y,...
                                      plywood_division_x,...
                                      plywood_division_y,...
                                      x_central_useful, ...
                                      y_central_useful, ...
                                      x_adj, ...
                                      y_adj, ...
                                      plot_enable);

fprintf('Calibration x-axis: x_real = %.4f x %.4f y + %.4f\n', Ahatx(1),Ahatx(2),Ahatx(3))
fprintf('Calibration y-axis: y_real = %.4f x %.4f y + %.4f\n', Ahaty(1),Ahaty(2),Ahaty(3))




