%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Design, modeling, and control of a low-cost air-bearing platform
%
% Software developed as part of the doctoral thesis.
%
% Author:      Luan Mateus Bocalan Vogás
% Advisor:     Prof. Dr. Roberto Kawakami Harrop Galvão
% Co-Advisor:  Profa. Dra. Gabriela Werner Gabriel
%
% Instituto Tecnológico de Aeronáutica (ITA)
% Electronics Engineering Division
% São José dos Campos, SP, Brazil
% 2026
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear all
close all
clc

%% Data loading 

[pusher_time_air, ...
 pusher_duty_air, ...
 pusher_force_air, ...
 tractor_time_air, ...
 tractor_duty_air, ...
 tractor_force_air, ...
 pusher_time_ducted, ...
 pusher_duty_ducted, ...
 pusher_force_ducted, ...
 tractor_time_ducted, ...
 tractor_duty_ducted, ...
 tractor_force_ducted ...
] = experimental_data_loading();

%% Air Duct Comparison 

plot_enable = 1;

air_duct_comparison(pusher_time_air, ...
                    pusher_force_air, ...
                    tractor_time_air, ...
                    tractor_force_air, ...
                    pusher_time_ducted, ...
                    pusher_force_ducted, ...
                    tractor_time_ducted, ...
                    tractor_force_ducted, ...
                    plot_enable)

